//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tarrahaan.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Global {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Global() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Tarrahaan.Resources.Global", typeof(Global).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About us.
        /// </summary>
        public static string aboutus {
            get {
                return ResourceManager.GetString("aboutus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        public static string all {
            get {
                return ResourceManager.GetString("all", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Asking Price.
        /// </summary>
        public static string askingprice {
            get {
                return ResourceManager.GetString("askingprice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bathroom(s).
        /// </summary>
        public static string bathroom {
            get {
                return ResourceManager.GetString("bathroom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bedroom(s).
        /// </summary>
        public static string bedroom {
            get {
                return ResourceManager.GetString("bedroom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Built up.
        /// </summary>
        public static string builtup {
            get {
                return ResourceManager.GetString("builtup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact us.
        /// </summary>
        public static string contactus {
            get {
                return ResourceManager.GetString("contactus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deposit Fee.
        /// </summary>
        public static string depositfee {
            get {
                return ResourceManager.GetString("depositfee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Land Area.
        /// </summary>
        public static string landarea {
            get {
                return ResourceManager.GetString("landarea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Update.
        /// </summary>
        public static string LastUpdate {
            get {
                return ResourceManager.GetString("LastUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latest Properties.
        /// </summary>
        public static string LatestProperties {
            get {
                return ResourceManager.GetString("LatestProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More Details.
        /// </summary>
        public static string moredetails {
            get {
                return ResourceManager.GetString("moredetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image Not Available.
        /// </summary>
        public static string NoImageAvailable {
            get {
                return ResourceManager.GetString("NoImageAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to of.
        /// </summary>
        public static string of {
            get {
                return ResourceManager.GetString("of", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Office.
        /// </summary>
        public static string office {
            get {
                return ResourceManager.GetString("office", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page.
        /// </summary>
        public static string page {
            get {
                return ResourceManager.GetString("page", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parking(s).
        /// </summary>
        public static string parking {
            get {
                return ResourceManager.GetString("parking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property Feature.
        /// </summary>
        public static string PropertyFeature {
            get {
                return ResourceManager.GetString("PropertyFeature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To Let.
        /// </summary>
        public static string rent {
            get {
                return ResourceManager.GetString("rent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rental Fee (Monthly).
        /// </summary>
        public static string rentalfee {
            get {
                return ResourceManager.GetString("rentalfee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For Sale.
        /// </summary>
        public static string sale {
            get {
                return ResourceManager.GetString("sale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tarahan aganecy | about us.
        /// </summary>
        public static string SeoDescription_About {
            get {
                return ResourceManager.GetString("SeoDescription_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tarahan aganecy | Contact us.
        /// </summary>
        public static string SeoDescription_Contact {
            get {
                return ResourceManager.GetString("SeoDescription_Contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tarahan aganecy | List of properties.
        /// </summary>
        public static string SeoDescription_ListProperties {
            get {
                return ResourceManager.GetString("SeoDescription_ListProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tarahan aganecy | Housing Agenecy in Tehran.
        /// </summary>
        public static string SeoDescription_MainPage {
            get {
                return ResourceManager.GetString("SeoDescription_MainPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tarahan aganecy  | Show property.
        /// </summary>
        public static string SeoDescription_ShowProperty {
            get {
                return ResourceManager.GetString("SeoDescription_ShowProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About us,Tarahan aganecy.
        /// </summary>
        public static string SeoKeyword_About {
            get {
                return ResourceManager.GetString("SeoKeyword_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to contact us,Tarahan aganecy.
        /// </summary>
        public static string SeoKeyword_Contact {
            get {
                return ResourceManager.GetString("SeoKeyword_Contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to rent,sale,buy,office,commercial,residential,apartment,villa,tehran,furnished.
        /// </summary>
        public static string SeoKeyword_ListProperties {
            get {
                return ResourceManager.GetString("SeoKeyword_ListProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to rent,sale,buy,tehran,furnished,tarrahaan.
        /// </summary>
        public static string SeoKeyword_MainPage {
            get {
                return ResourceManager.GetString("SeoKeyword_MainPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tarahan aganecy | About us.
        /// </summary>
        public static string SeoTitle_About {
            get {
                return ResourceManager.GetString("SeoTitle_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tarahan aganecy | Contact us.
        /// </summary>
        public static string SeoTitle_Contact {
            get {
                return ResourceManager.GetString("SeoTitle_Contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tarahan aganecy | Rent , Sale Property in Tehran.
        /// </summary>
        public static string SeoTitle_Home {
            get {
                return ResourceManager.GetString("SeoTitle_Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tarahan aganecy  | List Properties.
        /// </summary>
        public static string SeoTitle_ListProperties {
            get {
                return ResourceManager.GetString("SeoTitle_ListProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specifications.
        /// </summary>
        public static string specifications {
            get {
                return ResourceManager.GetString("specifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to m&lt;sup&gt;2&lt;/sup&gt;.
        /// </summary>
        public static string Sqrmeter {
            get {
                return ResourceManager.GetString("Sqrmeter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View.
        /// </summary>
        public static string view {
            get {
                return ResourceManager.GetString("view", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Villa.
        /// </summary>
        public static string villa {
            get {
                return ResourceManager.GetString("villa", resourceCulture);
            }
        }
    }
}
